version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - db-data:/data
    entrypoint: redis-server --appendonly yes
volumes:
  db-data:
    driver: local